### ISSUE TITLE
Could you please provide the dataset?

### ISSUE THREAD

**Issue by shuxiaobo** [dhanush987/MathematicalSymbolRecognition#2]
Hello, Thanks for your code , I want to build and run it ,but I can not run it without data, Could you please provide the dataset?

**Comment by youmizai** [comment]
the code is not available,there is not dataset ,and loss part code ,please add this project ,thanks

**Comment by dhanush-ai1990** [comment]
This is the dataset that needs to be downloaded: https://www.kaggle.com/xainano/handwrittenmathsymbols. I am not maintaining this anymore.

**Comment by shuxiaobo** [comment]
Great, Thank you a lot. @youmizai @dhanush987
